#!/bin/sh

[ $# -lt 2 ] && echo "Usage: $0 <key> <value>" && exit 1
KEY="$1" 
shift
VALUE="$*"

php -r "\$m = new Memcached();   \
\$m->addServer('localhost',11211);  \
\$m->setOption(Memcached::OPT_PREFIX_KEY, 'reqstat:');  \
\$m->set('"${KEY}"',\"${VALUE}\");" 

exit 0
